### ISSUE TITLE
Assets/Samples/OpenAI Unity/0.1.11/Whisper/Whisper.cs(45,36): error CS0433: The type 'Microphone' exists in both 'Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'UnityWebGLMicrophone, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by ymalegao** [bnco-dev/unity-webgl-microphone#1]
So If I already use the Microphone class from unity, what changes will I have to make to get it to build properly? Do I just have to use the namespace that is used in the looping script?

**Comment by bnco-dev** [comment]
Did you import the package or just grab the Microphone.cs class? The .asmdef in the package should mean the package is only used in WebGL builds so you wouldn't get the above error.

About changes you need to make - it's basically just a drop-in replacement. The only thing to keep in mind is that the microphone won't start if you haven't interacted with the page yet, so wait to call Microphone.Start until after that has happened (or just call it in a loop, like in the sample script, until it returns a clip).

**Comment by ymalegao** [comment]
if you have time, is there a place where I could contact you? I am a student working on a project and it would help greatly!
