### ISSUE TITLE
Microphone.IsRecording(string) does not return the right value

### ISSUE THREAD

**Issue by qsy1999** [bnco-dev/unity-webgl-microphone#3]
This function always returns false.

The function JS_Microphone_IsRecording() in your jslib may not return a bool value.

In javascript , `return ctx && ctx.stream;` will actually return ctx.stream when it is expected to return true , making Microphone.IsRecording(string) returns wrong bool value

Change that line into
```
if (ctx && ctx.stream) 
    return true;
else
    return false;
```
and the problem is resolved

**Comment by bnco-dev** [comment]
Ah Javascript! Thanks for the report.
